In [2]:
!pip install opencv-python

In [3]:
import cv2
import numpy as np

In [4]:
img=cv2.imread(r"C:\Users\LoQ\Desktop\AI\(AI) Deep learning\CV\chetna.jpeg",1)

In [5]:

print(img)

[[[220 218 230]
  [220 218 230]
  [220 218 230]
  ...
  [ 53  45  55]
  [ 84  76  86]
  [104  96 106]]

 [[220 218 230]
  [220 218 230]
  [220 218 230]
  ...
  [ 54  46  56]
  [ 85  77  87]
  [104  96 106]]

 [[220 218 230]
  [220 218 230]
  [220 218 230]
  ...
  [ 54  46  56]
  [ 84  76  86]
  [102  94 104]]

 ...

 [[ 71  70  80]
  [ 76  75  85]
  [ 79  78  88]
  ...
  [ 88  82  93]
  [ 90  84  95]
  [ 85  79  90]]

 [[ 75  74  84]
  [ 81  80  90]
  [ 83  82  92]
  ...
  [ 76  70  81]
  [ 81  75  86]
  [ 78  72  83]]

 [[ 74  73  83]
  [ 80  79  89]
  [ 81  80  90]
  ...
  [ 62  56  67]
  [ 70  64  75]
  [ 71  65  76]]]


In [6]:
img.shape

(1328, 1600, 3)

In [7]:
cv2.imshow('PM',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
cv2.imwrite("chetna.jpeg",img)

True

In [9]:
img=cv2.imread(r"C:\Users\LoQ\Desktop\AI\(AI) Deep learning\CV\chetna.jpeg")
resized_image=cv2.resize(img,(500,500))
gray=cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)
cv2.imshow("chetna Image",gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
img.shape[0]*0.5

664.0

In [11]:
img.shape[1]*0.5

800.0

In [12]:
import cv2

print(cv2.__file__)
print(cv2.__version__)

C:\Users\LoQ\anaconda3\Lib\site-packages\cv2\__init__.py
4.10.0


In [13]:
print(hasattr(cv2, "CascadeClassifier"))

True


In [14]:
!pip uninstall opencv-python opencv-contrib-python opencv-python-headless opencv-contrib-python-headless -y

Found existing installation: opencv-python 4.10.0.84
Uninstalling opencv-python-4.10.0.84:
  Successfully uninstalled opencv-python-4.10.0.84


You can safely remove it manually.


In [15]:
!pip install opencv-python==4.10.0.84

  Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl (38.8 MB)


In [16]:
import cv2

print(cv2.__version__)
print(hasattr(cv2, "CascadeClassifier"))

4.10.0
True


In [17]:
face_classifier = cv2.CascadeClassifier(r"C:\Users\LoQ\Desktop\AI\(AI) Deep learning\CV\haarcascade_frontalface_default.xml")

In [18]:
print(face_classifier.empty)

<built-in method empty of cv2.CascadeClassifier object at 0x000001A5D185C690>


In [19]:
image=cv2.imread(r"C:\Users\LoQ\Desktop\AI\(AI) Deep learning\CV\chetna.jpeg")
image=cv2.resize(image,(500,500))
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

In [20]:
faces = face_classifier.detectMultiScale(gray,1.3,10)

In [21]:
print(faces)

[[165  61 167 167]]


In [22]:
if faces is ():
    print("No faces found")
for(x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,100),1)
cv2.imshow("Face Detection",image)
cv2.waitKey()
cv2.destroyAllWindows()

<>:1: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
C:\Users\LoQ\AppData\Local\Temp\ipykernel_19224\2315688867.py:1: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
  if faces is ():


In [23]:
import cv2

In [24]:
face_classifier=cv2.CascadeClassifier(r"C:\Users\LoQ\Desktop\AI\(AI) Deep learning\CV\haarcascade_frontalface_default.xml")

In [25]:
eye_Classifier=cv2.CascadeClassifier(r"C:\Users\LoQ\Desktop\AI\(AI) Deep learning\CV\haarcascade_eye.xml")

In [26]:
img=cv2.imread(r"C:\Users\LoQ\Desktop\AI\(AI) Deep learning\CV\chetna.jpeg")
resized_image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)


In [27]:
faces = face_classifier.detectMultiScale(gray,1.3,5)

In [28]:
if faces is ():
    print("No Face Found")
for (x,y,w,h) in faces:
    cv2.rectangle(resized_image,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = resized_image[y:y+h, x:x+w]
    eyes = eye_Classifier.detectMultiScale(roi_gray)
    for(ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    
cv2.imshow("img",resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows() 



In [29]:
import cv2

video = cv2.VideoCapture(0)

while True:
    check, frame = video.read()

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    cv2.imshow("Video", gray)

    if cv2.waitKey(1)  == ord('q'):
        break

video.release()
cv2.destroyAllWindows()

In [30]:
import cv2

In [31]:
face_cascade=cv2.CascadeClassifier(r"C:\Users\LoQ\Desktop\AI\(AI) Deep learning\CV\haarcascade_frontalface_default.xml")

In [32]:
eye_cascade=cv2.CascadeClassifier(r"C:\Users\LoQ\Desktop\AI\(AI) Deep learning\CV\haarcascade_eye.xml")

In [33]:
import cv2

video = cv2.VideoCapture(0)

print("Camera opened:", video.isOpened())

check, frame = video.read()

print("Frame received:", check)

if check:
    cv2.imshow("Camera Test", frame)
    cv2.waitKey(0)

video.release()
cv2.destroyAllWindows()

Camera opened: True
Frame received: True


In [34]:
def detect(gray,frame):
    faces = face_cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray,1.1,3)
        for(ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    return frame

In [ ]:
video = cv2.VideoCapture(0)
while True:
    check , frame =video.read()
    gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    canvas = detect(gray,frame)
    cv2.imshow('Video', canvas)
    
    if cv2.waitKey(1) == ord('q'):
        break
video.release()
cv2.destroyAllWindows()